### ISSUE TITLE
Could not download MeiWidgetView.aar

### ISSUE THREAD

**Issue by YiBei1223** [HpWens/MeiWidgetView#12]
这个是要设置代理嘛 我连依赖都依赖不了

**Comment by HpWens** [comment]
帅哥，你好。我测试可以正常依赖。。请检测是否少了   maven { url 'https://jitpack.io' }  这个仓库

**Comment by YiBei1223** [comment]
可能是我今天公司网络不好 明天我再试试 仓库地址我都是有的
![image](https://user-images.githubusercontent.com/33239884/58314964-2f1f4d80-7e43-11e9-8131-e10123b57bb6.png)

**Comment by HpWens** [comment]
![Uploading image.png…]()

**Comment by HpWens** [comment]
![image](https://user-images.githubusercontent.com/13116096/58320164-a5c14880-7e4d-11e9-9ad8-da66ce527627.png)

**Comment by HpWens** [comment]
帅哥你好，我这边依赖都没问题。。请检查你网络问题，host文件？

**Comment by YiBei1223** [comment]
嗯嗯 已解决 谢谢了
