### ISSUE TITLE
APK在android 9.0上安装失败

### ISSUE THREAD

**Issue by xluu233** [HpWens/MeiWidgetView#6]
机型：小米8 androdi9.0
提示：其他原因

**Comment by TWBfly** [comment]
![image](https://user-images.githubusercontent.com/21956119/50256839-3c1eb780-0433-11e9-8357-4ae7e0ba0d54.png)
apk是debug包，装不上，作者请打个release包

**Comment by HpWens** [comment]
大佬。已处理。抱拳
